### ISSUE TITLE
type="module" not required

### ISSUE THREAD

**Issue by Danny-Engelman** [daviddarnes/is-playing#1]
Your Web Components needs to read the component lightDOM/innerHTML; which is not available because the ``connectedCallback`` fires on the **opening tag**  
That is why you (need to) use ``type="module"``, it forces the script to delay until the whole DOM page is parsed.

You can put a lesser delay in the ``connectedCallback`` [with a ``setTimeout`` or other techniques](https://dev.to/dannyengelman/web-component-developers-do-not-connect-with-the-connectedcallback-yet-4jo7)

Since you are not attaching multiple Listeners, ``addEventListener`` is not required also.

That minimizes (for best GZipped delivery) your code to, which can now be placed in a ``<script>`` tag inside the ``<head>``

```javascript
  customElements.define("is-playing", class extends HTMLElement {
    connectedCallback() {
      setTimeout(() => // wait till lightDOM is parsed
        this.querySelectorAll("audio,video").forEach(p =>
          Object.assign(p, {
            onplaying: _ => {
              p.setAttribute("playing", "");
              this.setAttribute("playing", p.id || "");
            },
            onpause: _ => {
              p.removeAttribute("playing");
              this.removeAttribute("playing");
            },
            onended: _ => {
              p.removeAttribute("playing");
              this.removeAttribute("playing");
            }
          }) // Object.assign
        ) // forEach
      ) // setTimeout
    } // connectedCallback
  }); // define
```

**Comment by daviddarnes** [comment]
Please stop spamming my open source projects. I've seen your behaviour on here, finding open source Web Components across GitHub and attempting to enforce an approach that just suits your desired outcomes. It's not constructive to the community.

I've already explained multiple times why my Web Components are written like this. They are designed to enhance regular HTML, so I **want** to wait until the DOM is loaded before applying this extra interactivity. That's how progressive enhancement works. In addition, I don't want my code to be readable, so others can learn and contribute with ease.
